[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"

[context.production.environment]
  HUGO_VERSION = "0.29"
  YARN_VERSION = "1.1.0"
