baseurl = "https://javascript.sg/"
languageCode = "en-us"
title = "JavaScript.sg"
theme = "embryo"
titleCaseStyle = "AP"
googleAnalytics = "UA-175843-10"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
  name = "KahWee Teng"
  description = "Describe your website"
  bio = "Blogger & Programmer"
  # Enter optionally your twitter account
  twitter = "kahwee"
  enableRSS = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "A local foreigner."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

[[menu.main]]
  name = "About"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "about"
  url = "/pages/about/"

# Add additional social link entries underneath
[social]
  twitter  = "https://www.twitter.com/kahwee"
  facebook = "https://www.facebook.com/kahwee"
  github   = "https://www.github.com/kahwee"
